# Generated by Django 4.1.5 on 2023-01-11 14:25

import datetime
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=posts.models.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("date", models.DateField(max_length=25)),
                ("publish_date", models.DateField(default=datetime.date(2023, 1, 11))),
                ("is_published", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("rendered_content", models.TextField()),
            ],
            options={
                "ordering": ["-publish_date"],
            },
        ),
    ]
